### PR TITLE
Installation & Migration issues

### PR DESCRIPTION
**Pull request by charles-marion**
I tried to migrate an instance and I wasn't able to login (because of the secure cookie flag).
I also tried to install Midas and it didn't work. A folder was not writable and I didn't get a message.

I fixed these issues.

### CODE REVIEW

**Comment by zachmullen** [comment]
This smells of needing a reusable function.

**Comment by cpatrick** [comment]
@zachmullen You're right about that :smile: 

@charles-marion @jamiesnape In terms of the default value of the secure cookie field, I'm torn. If the server is running over HTTPS using `secure` is almost certainly what they want, but it does add an extra step to the upgrade of old systems.

**Comment by jamiesnape** [comment]
The secure cookie setting is not a bug. I will update the documentation before the release.

**Comment by jamiesnape** [comment]
The permissions issue needs to be fixed in an alternate way. This fix breaks App Engine support.

**Comment by jamiesnape** [comment]
I think the issue for both this issues is that it just needs documentation, and I will work on that when I have time. The simple fact is that the installation and upgrade process is not identical to how it was in the previous version, and that is deliberate for security and cloud compatibility reasons.

**Comment by jamiesnape** [comment]
Issue #88 created for documentation.

**Comment by charles-marion** [comment]
Right now, if you install MIDAS on Linux. It tells you "Your system is Ok". You click on Next and nothing happen.

If you migrate (still on linux)  your instance, you cannot log in and you don't know why.
Also if you were using the developpement mode, your  instance became very slow and you don't know why.

In my opinion these are major issues and should be fixed...

**Comment by jamiesnape** [comment]
@charles-marion Hence, why I need to update the documentation.

**Comment by jcfr** [comment]
@charles-marion Thanks for your contribution :+1: 

@jamiesnape Could the user be notified with a meaningful message ? 

While discussing the secure cookie setting,  could the commit 3ffe103 be integrated ? Seems this one is not subject to controversy.

**Comment by jamiesnape** [comment]
@jcfr No, it will break App Engine support.

**Comment by jamiesnape** [comment]
@jcfr Not really. You are checking whether a folder is writeable, but there is no concept of folders on Cloud Storage.

**Comment by jcfr** [comment]
@jamiesnape I see. Do this mean such check should be done on a per asset store basis ? Midas should check if the given asset store is writable etc ...

**Comment by jamiesnape** [comment]
@jcfr It should, but that would not help, unfortunately, as Midas handles configuration files differently to other files. The problem is that config files are copied to another location altogether during installation (not an asset store). 

The correct solution, I think, is to move the configuration (other than of the database connection) to the database. I have a prototype of that (I demonstrated it in a tech tip), but it is some way from being ready for testing. That also has the side effect of significant performance improvements.

**Comment by jcfr** [comment]
@jamiesnape Thanks for the detailed explanation. Look like there are some exciting changes on the way. I like the idea of having the database being the only entity representing the state of a server.

**Pull request closed without merging**
