### PR TITLE
Fix upgrade tab

### PR DESCRIPTION
**Pull request by jamiesnape**
There are about three ways to find a module version and apparently I did not notice this was using the wrong one. Future work is to obliterate those other ways. :boom:

### CODE REVIEW

**Comment by jamiesnape** [comment]
@cpatrick @mgrauer PTAL.

**Comment by cpatrick** [comment]
LGTM in principle, but I'd like @mgrauer to verify on #127.

**Comment by mgrauer** [comment]
LGTM pending travis.

**Comment by jamiesnape** [comment]
Travis will pass. There are no tests for the changed part...

**Comment by jamiesnape** [comment]
(cue mass failure of tests)

**Pull request merged**
