### PR TITLE
Specify Directory AllowOverride in docs

### PR DESCRIPTION
**Pull request by mgrauer**
@jamiesnape PTAL.

### CODE REVIEW

**Comment by jamiesnape** [comment]
LGTM.

**Comment by jamiesnape** [comment]
Apparently Ansible had the right idea, but it never made it to the docs:

[provisioning/ansible/roles/apache2/templates/etc-apache2-sites-available-vagrant.conf.j2#L5](https://github.com/midasplatform/Midas/blob/master/provisioning/ansible/roles/apache2/templates/etc-apache2-sites-available-vagrant.conf.j2#L5)

**Comment by mgrauer** [comment]
I've updated to be consistent with Ansible.  PTAL.

**Comment by jamiesnape** [comment]
LGTM.

**Pull request merged**
