### PR TITLE
Format Scalar details Value to 4 decimals

### PR DESCRIPTION
**Pull request by mgrauer**
A stray scalar that I neglected to format earlier.

### CODE REVIEW

**Comment by mgrauer** [comment]
@jamiesnape This PR is failing style checks on files I didn't touch.  Would you like me to fix the styles on this branch or ?

**Comment by jamiesnape** [comment]
@mgrauer Not sure what was going on. I disabled tests for `library/REST` and quickly fixed the remaining so you are good to go as far as style is concerned.

**Comment by mgrauer** [comment]
Thanks @jamiesnape .  This is RFR.

**Comment by cpatrick** [comment]
LGTM!

**Pull request merged**
