### PR TITLE
Rename aggregate_metric_spec col schema to spec

### PR DESCRIPTION
**Pull request by mgrauer**
`schema` is a reserved word in SQL, `spec` isn't.

@jamiesnape @cpatrick  PTAL

### CODE REVIEW

**Comment by cpatrick** [comment]
LGTMIAWTIH

**Comment by mgrauer** [comment]
Travis may never be happy, even if he should be.

**Comment by cpatrick** [comment]
The push check passing is good enough for me.

**Comment by mgrauer** [comment]
I take it back, my apologies Travis.

**Pull request merged**
