### PR TITLE
Fix submission producer create

### PR DESCRIPTION
**Pull request by cpatrick**

### CODE REVIEW

**Comment by cpatrick** [comment]
@mgrauer PTAL.

**Comment by mgrauer** [comment]
Very nice.

Can you changes these docblock comments on the [submission.add](https://github.com/midasplatform/Midas/blob/8f309110921f059f0cb344cf94157d9f71b884c0/modules/tracker/controllers/components/ApiComponent.php#L310-L320) API endpoint?  They are out of sync with the [submission POST endpoint](https://github.com/midasplatform/Midas/blob/8f309110921f059f0cb344cf94157d9f71b884c0/modules/tracker/controllers/components/ApisubmissionComponent.php#L127-L146) that submission.add forwards on to.  Also mention that write access on the community is required, similar to scalarAdd, in the submission.add function description.

Otherwise LGTM.

**Comment by mgrauer** [comment]
@cpatrick PTAL.  This is good from my end.

**Comment by cpatrick** [comment]
Your changes lgtm. I'll merge once Travis is happy.

**Pull request merged**
