### PR TITLE
Update "uploadPerform" to set "Initial revision" if it applies

### PR DESCRIPTION
**Pull request by jcfr**
This commit ensures that the first revision of new item will always be
associated with the comment "Initial revision". This applies to new files
uploaded using either the web apis or the web interface.

The behavior is now consistent with the initial message set in
UploadComponent::createLinkItem() and ApisystemComponent::uploadGeneratetoken()

### CODE REVIEW

**Comment by jcfr** [comment]
Cc: @cpatrick @jamiesnape

**Comment by jcfr** [comment]
To illustrate, when uploading a new file:

* Before this change:

midas-before-pr-update-api-uploadperform-to-set-changes-for-initial-revision

* After this change:

midas-after-pr-update-api-uploadperform-to-set-changes-for-initial-revision

**Comment by jamiesnape** [comment]
I do not think having a description "Initial revision" really adds anything. Revision 1 is obviously the initial revision. Is there a compelling reason why this is required?

**Comment by jcfr** [comment]
Consistency with what was done in `UploadComponent::createLinkItem()` and `ApisystemComponent::uploadGeneratetoken()`. I guess we could remove it everywhere or add it every where ... let me know.

**Comment by jamiesnape** [comment]
I think remove it.

**Pull request closed without merging**
