### PR TITLE
3.4: Security fixes, library upgrades, replacement of smart optimizer with SASS, formatting, cloud-related enhancements

### PR DESCRIPTION
**Pull request by jamiesnape**
Most of this has been tested for a month or so with no issues so far.

### CODE REVIEW

**Comment by cpatrick** [comment]
@jamiesnape I've deployed this on an older, exotic Midas instance and everything worked well. This is great. It's still set to be Midas 3.2.20, though. Do we want to go to 3.4.0 on this branch?

Actually, I'll go ahead and say that should be in another PR.

**Comment by cpatrick** [comment]
[LGTM](http://www.lgtm.in/i/wQgMfYynq)

**Comment by jamiesnape** [comment]
Yes, lets do another branch. There are a couple more form-related changes I need to cherry pick from elsewhere and then the versioning to do. Tracker Dashboard 2.0, may also make it into the release.

**Comment by jcfr** [comment]
Is there anything in existing plugin that should be updated ?

--

**Comment by jamiesnape** [comment]
It is intended to be entirely backward compatible with respect to modules. I will write some release notes all the same.

**Comment by jcfr** [comment]
+1 This is awesome. Thanks for all your work on this.

On Thu, Jan 8, 2015 at 12:29 PM, Jamie Snape <notifications@github.com>
wrote:

> It is intended to be entirely backward compatible with respect to modules.
> I will write some release notes all the same.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/midasplatform/Midas/pull/76#issuecomment-69215441>.
>



-- 
+1 919 869 8849

**Pull request merged**
