### PR TITLE
Remove community shared with members tab

### PR DESCRIPTION
**Pull request by mgrauer**
@cpatrick PTAL.

The data to populate this tab could be expensive to load, and doesn't provide much value.

### CODE REVIEW

**Comment by jamiesnape** [comment]
As far as I know, the function in the Item model is not used anywhere else.

**Comment by mgrauer** [comment]
Giant style fix, as far as I can tell, this only removes periods from the EOL of API doc comments.

**Comment by mgrauer** [comment]
Thanks @jamiesnape .  I don't see any other use of that function and it has no test, I'll delete it.

**Comment by cpatrick** [comment]
LGTM.

**Pull request merged**
