### PR TITLE
Fix thumbnailer (again)

### PR DESCRIPTION
**Pull request by jamiesnape**
The module should really just be rewritten from scratch.

@cpatrick @mgrauer PTAL.

### CODE REVIEW

**Comment by mgrauer** [comment]
Why this change?

**Comment by jamiesnape** [comment]
Because it is trying to thumbnail everything, text files and binaries included.

**Comment by mgrauer** [comment]
LGTM

**Comment by jamiesnape** [comment]
:camel: ?

**Comment by mgrauer** [comment]
yes, :camel: , sorry for the confusion

**Pull request merged**
